build: off

platform: x64

clone_folder: c:\gopath\src\github.com\gky360\atcli

environment:
  GOPATH: c:\gopath

stack: go 1.12

install:
  - echo %PATH%
  - echo %GOPATH%
  - set PATH=%GOPATH%\bin;c:\go\bin;%PATH%
  - go version
  - go env

test_script:
  - go test -v -race ./...
